# https://taskfile.dev

version: "3"

vars:
  IMAGES:
    - debian:latest
    - alpine:latest
    - mcr.microsoft.com/devcontainers/base:ubuntu

tasks:
  default:
    cmds:
      - task: test

  test:
    desc: Test all features
    cmd:
      for: { var: IMAGES }
      cmd: devcontainer features test --base-image {{.ITEM}}
